name: Python Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up .NET SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' 
        java-version: '21'
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: 21
        maven-version: '3.9.6'
    # section only required while we need the temp package
    - run: mkdir $GITHUB_WORKSPACE/packages
    - run: echo "CEDISCO_NUGET_LOCAL_FEED=$GITHUB_WORKSPACE/packages" >> $GITHUB_ENV
    - name: Get CloudNative.CloudEvents.Endpoint package code
      uses: actions/checkout@v3
      with:
        repository: clemensv/CloudNative.CloudEvents.Endpoints
        ref: main
        path: csendpoints
    - name: build CloudNative.CloudEvents.Endpoint package code
      run: dotnet build $GITHUB_WORKSPACE/csendpoints/source/CloudNative.CloudEvents.Experimental.Endpoints.sln
    - name: create package into temp feed 
      run: cp $GITHUB_WORKSPACE/csendpoints/source/packages/* $GITHUB_WORKSPACE/packages 
    - name: Get CloudNative.CloudEvents.Endpoint package code (java)
      uses: actions/checkout@v3
      with:
        repository: clemensv/io.cloudevents.experimental.endpoints
        ref: main
        path: javaendpoints
    - name: build CloudNative.CloudEvents.Endpoint package code
      run: mvn install -f $GITHUB_WORKSPACE/javaendpoints/pom.xml
    # end section
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    # we need to build the package for generating the _version.py file that isn't checked in
    - name: Install dependencies and build package
      run: |
        python -m pip install --upgrade pip build wheel
        python -m pip install -r requirements.txt
        python -m build --sdist --wheel --outdir dist
    - name: Install Test Prerequesites
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true 
        npm install -g @asyncapi/cli
        npm install -g @openapitools/openapi-generator-cli      
    - name: Run tests
      run: |
        pytest

